---

# Введение в NumPy


Импортируем $\mathsf{numpy}$:

In [1]:
import numpy as np

---

## 4 | Продвинутые возможности

---

### 4.1 | Немного о линейности операций

---

Матрица поддерживают операции добавления (вычитания) и умножения (деления) на некоторое число всех элементов, а также возведения значений матрицы в некоторую степень:

In [2]:
arr = np.array([1, 4])
arr

array([1, 4])

In [3]:
arr + 4

array([5, 8])

In [4]:
arr * -1

array([-1, -4])

In [5]:
arr ** 3

array([ 1, 64])

---

Также эти операции поддерживаются между двумя матрицами одинаковой формы:

In [6]:
a = np.array([-1, 2])
a

array([-1,  2])

In [7]:
b = np.array([1, 3])
b

array([1, 3])

In [8]:
a + b

array([0, 5])

In [9]:
a * b

array([-1,  6])

In [10]:
a ** b

array([-1,  8])

---

Кроме предыдущих случаев, эти операции поддерживаются и над двумя матрицами. При этом, вторая матрица должна иметь форму, содержащуюся в форме первой:

In [11]:
a = np.arange(12).reshape((2, 3, 2))
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [12]:
b = np.array([0, 0, -1, 1, -100, 100]).reshape((3, 2))
b

array([[   0,    0],
       [  -1,    1],
       [-100,  100]])

In [13]:
a + b

array([[[  0,   1],
        [  1,   4],
        [-96, 105]],

       [[  6,   7],
        [  7,  10],
        [-90, 111]]])

In [14]:
a * b

array([[[    0,     0],
        [   -2,     3],
        [ -400,   500]],

       [[    0,     0],
        [   -8,     9],
        [-1000,  1100]]])

---

### 4.2 | В дополнение о форме

---

Начнем с функции $\mathsf{np.flip}$, разворачивающей содержимое массива целиком или вдоль оси:

In [15]:
arr = np.arange(1, 13).reshape((3, 4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
np.flip(arr)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [17]:
np.flip(arr, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [18]:
np.flip(arr, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

С помощью этой функции можно выполнять такие трюки, как реверс строки или колонки:

In [19]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr1, arr2 = arr.copy(), arr.copy()

arr1[1] = np.flip(arr[1])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [21]:
arr2[:, 1] = np.flip(arr[:, 1])
arr2

array([[ 1, 10,  3,  4],
       [ 5,  6,  7,  8],
       [ 9,  2, 11, 12]])

---

Транспонирование матриц производится с помощью метода $\mathsf{transpose}$:

In [22]:
arr = np.arange(1, 9).reshape((2, -1))
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

---

### Функции для сбора статистики

---

Для сбора уникальных значений существует функция $\mathsf{np.unique}$:

In [24]:
arr = np.array([1, 1, 1, 4, 5, 7, 4, 5])
np.unique(arr)

array([1, 4, 5, 7])

Если поставить флаг $\mathsf{return\_index}$, то мы получим список индексов первого вхождения представленных уникальных элементов:

In [25]:
arr

array([1, 1, 1, 4, 5, 7, 4, 5])

In [26]:
unique_values, indices_list = np.unique(arr, return_index=True)
unique_values

array([1, 4, 5, 7])

In [27]:
indices_list

array([0, 3, 4, 5])

Функция поддерживает также выбор $\mathsf{axis}$:

In [28]:
arr = np.array([
    [1, 2, 3, 1],
    [5, 6, 7, 5],
    [9, 10, 11, 9],
    [1, 2, 3, 1]
])
arr

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  5],
       [ 9, 10, 11,  9],
       [ 1,  2,  3,  1]])

In [29]:
np.unique(arr, axis=0)

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  5],
       [ 9, 10, 11,  9]])

In [30]:
np.unique(arr, axis=1)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [ 1,  2,  3]])

In [31]:
np.unique(arr)

array([ 1,  2,  3,  5,  6,  7,  9, 10, 11])

Функцию также можно попросить вернуть нам встречаемость соответствующих элементов, используя параметр $\mathsf{return\_counts}$:

In [32]:
unique_rows, indices, occurrence_count = np.unique(
    arr, axis=0, return_counts=True, return_index=True)
unique_rows

array([[ 1,  2,  3,  1],
       [ 5,  6,  7,  5],
       [ 9, 10, 11,  9]])

In [33]:
indices

array([0, 1, 2])

In [34]:
occurrence_count

array([2, 1, 1])

---

Конструкции библиотеки позволяют нам, например, быстро и понятно имплиментировать выражение для подсчета среднеквадратичного отклонения:

$$
MeanSquareError = \dfrac{1}{n}\sum\limits_{i=1}^n\left(Y\_prediction_i - Y\_real_i\right)^2
$$

Средствами чистого $\mathsf{python}$ это можно сделать так:

In [35]:
# Пример инициализации
n = 10
y_pred = [1.1, 2.0, 2.9, 2.4, 1.0, 1.3, 2.2, 2.5, 3.0, 1.9]
y_real = [1.0, 2.0, 3.0, 2.5, 1.0, 1.0, 2.5, 2.5, 3.0, 2.0]

# Сама функция

mean_square_error = 0

for i in range(n):
    mean_square_error += (y_pred[i] - y_real[i]) ** 2
mean_square_error /= n

mean_square_error

0.022

Или для тех, кто опытен в использовании этого языка программирования:

In [36]:
# Пример инициализации
n = 10
y_pred = [1.1, 2.0, 2.9, 2.4, 1.0, 1.3, 2.2, 2.5, 3.0, 1.9]
y_real = [1.0, 2.0, 3.0, 2.5, 1.0, 1.0, 2.5, 2.5, 3.0, 2.0]

# Сама функция

mean_square_error = sum([(i_pred - i_real) ** 2
    for i_pred, i_real in zip(y_pred, y_real)]) / n

mean_square_error

0.022

А вот, чего можно добиться, используя лишь средства $\mathsf{numpy}$:

In [37]:
# Пример инициализации

n = 10
y_pred = np.array([
    1.1, 2.0, 2.9, 2.4, 1.0, 1.3, 2.2, 2.5, 3.0, 1.9])
y_real = np.array([
    1.0, 2.0, 3.0, 2.5, 1.0, 1.0, 2.5, 2.5, 3.0, 2.0])

# Сама функция

mean_square_error = np.sum((y_pred - y_real) ** 2) / n

mean_square_error

0.022

---