---

# Введение в NumPy


In [1]:
import numpy as np

---

## 2 | Многомерные матрицы

---

### 2.1 | Способы инициализации

---

С помощью вложенного списка:

In [2]:
np.array([[1, 4, 9], [2, 3, 5]])

array([[1, 4, 9],
       [2, 3, 5]])

---

Инициализировать массив списками разной длинны нельзя — получите предупреждение:

In [3]:
np.array([[1, 2], [4]])

<ipython-input-3-addf891ff8cb>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2], [4]])


array([list([1, 2]), list([4])], dtype=object)

---

У матриц также можно узнать их форму и размер:

In [4]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.shape)
print(arr.size)
arr

(3, 2)
6


array([[1, 2],
       [3, 4],
       [5, 6]])

---

Стандартные функции инициализации матриц также поддерживают указание форм массивов:

In [5]:
zeros_arr = np.zeros((2, 3))
print(zeros_arr.shape)
zeros_arr

(2, 3)


array([[0., 0., 0.],
       [0., 0., 0.]])

---

Для загрузки массивов в файл с расширением $\mathsf{npy}$ и считывания из него есть фукнции $\mathsf{np.save}$ и $\mathsf{np.load}$:

In [6]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
np.save('data', arr)
loaded = np.load('data.npy')
loaded

array([[1, 2],
       [3, 4],
       [5, 6]])

---

Для сохранения данных в файл формата $\mathsf{txt}$ существуют аналогичные по интерфейсу функции $\mathsf{np.savetxt}$ и $\mathsf{np.loadtxt}$:

In [7]:
np.savetxt('data.txt', arr)
txt_loaded = np.loadtxt('data.txt')
txt_loaded

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

---

### 3.2 | Основной функционал

---

В некоторых функциях и методах есть $\mathsf{axis}$, отвечающий за то, вдоль какой оси им работать:

In [8]:
zeros_arr = np.zeros((2, 3))
arr = np.array([[1, 2, 3], [4, 5, 6]])

np.append(zeros_arr, arr)

array([0., 0., 0., 0., 0., 0., 1., 2., 3., 4., 5., 6.])

In [9]:
np.append(zeros_arr, arr, axis=0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [10]:
np.append(zeros_arr, arr, axis=1)

array([[0., 0., 0., 1., 2., 3.],
       [0., 0., 0., 4., 5., 6.]])

---

Даже такие функции, как $\mathsf{np.sort}$ поддерживают указание $\mathsf{axis}$:

In [11]:
arr = np.array([[4, 5, 6], [3, 1, 2]])
np.sort(arr)

array([[4, 5, 6],
       [1, 2, 3]])

In [12]:
np.sort(arr, axis=0)

array([[3, 1, 2],
       [4, 5, 6]])

In [13]:
np.sort(arr, axis=1)

array([[4, 5, 6],
       [1, 2, 3]])

---

Такие функции, как $\mathsf{np.min}$, $\mathsf{np.max}$ и $\mathsf{np.sum}$ (взятие минимума, максимума и суммирование), поддерживают использование параметра $\mathsf{axis}$:

In [14]:
arr = np.array([[1, 1], [3, 5], [-1, -10]])
arr

array([[  1,   1],
       [  3,   5],
       [ -1, -10]])

In [15]:
arr.max()

5

In [16]:
arr.max(axis=0)

array([3, 5])

In [17]:
arr.max(axis=1)

array([ 1,  5, -1])

In [18]:
arr.sum()

-1

In [19]:
arr.sum(axis=0)

array([ 3, -4])

In [20]:
arr.sum(axis=1)

array([  2,   8, -11])

---

Менять форму массива можно с помощью функции $\mathsf{np.reshape}$ или аналогичного метода $\mathsf{reshape}$:

In [21]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [22]:
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

---

Если мы не знаем количество элементов на какой-то оси, то можно писать $-1$, подразумевая под этим <<сколько влезет>>:

In [23]:
b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [24]:
b.reshape((-1)) # Аналог np.reshape(b, (-1))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
b.reshape((2, -1)) # Аналог np.reshape(b, (2, -1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

---

Вместо преобразования к форме $(-1)$ можно воспользоваться методом $\mathsf{flatten}$:

In [26]:
arr = np.arange(1, 13).reshape((2, 3, 2))
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [27]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

---

Преобразовывать надо аккуратно — при преобразовании к неправильной форме может возникнуть ошибка:

In [28]:
arr = np.arange(5)
arr.reshape((2, 2)) # Или даже arr.reshape((2, -1))

ValueError: ignored

---

Для добавления форме фиктивной оси с одной стороны можно использовать метод $\mathsf{reshape}$:

In [29]:
arr = np.arange(6)
arr.reshape((1, -1))

array([[0, 1, 2, 3, 4, 5]])

In [30]:
arr.reshape((-1, 1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [31]:
arr.reshape(-1), arr.flatten()

(array([0, 1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4, 5]))

---

Можно добиться того же самого с использованием функции $\mathsf{np.expand\_dims}$:

In [32]:
np.expand_dims(arr, axis=0)

array([[0, 1, 2, 3, 4, 5]])

In [33]:
np.expand_dims(arr, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

---