---

# Введение в NumPy


---

## 1 | Одномерные массивы

Импортируем $\mathsf{numpy}$:

In [1]:
import numpy as np

---

### 1.1 | Способы инициализации

---

Инициализация $\mathsf{np.array}$ помощью $\mathsf{list}$:

In [2]:
[1, 4, 9]

[1, 4, 9]

In [3]:
np.array([1, 4, 9])

array([1, 4, 9])

In [4]:
type([1, 4, 9])

list

In [5]:
type(np.array([1, 4, 9]))

numpy.ndarray

---

С помощью встроенных функций $\mathsf{zeros}$, $\mathsf{ones}$ и $\mathsf{empty}$:

In [6]:
np.zeros(4) # Заполняет нулями

array([0., 0., 0., 0.])

In [7]:
np.ones(3) # Заполняет единицами

array([1., 1., 1.])

In [8]:
np.empty(2) # Заполняет память и выдает случайные значения

array([-5.73021895e-300,  6.92143851e-310])

---

Функции $\mathsf{np.arange}$ и $\mathsf{np.linspace}$:

In [9]:
np.arange(0, 9, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0, 9, 3)

array([0, 3, 6])

In [11]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

---

При инициализации данных мы можем явно задавать тип:

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones(4, dtype=np.int64)

array([1, 1, 1, 1])

---

### 1.2 | Основной функционал

---

Можно удалять и добавлять элементы с помощью функций $\mathsf{np.delete}$ и $\mathsf{np.append}$:

In [14]:
arr = np.array([1, 3, 9, 0])
np.append(arr, 16) # Добавление одного элемента

array([ 1,  3,  9,  0, 16])

In [15]:
np.append(arr, [16, 25]) # Нескольких

array([ 1,  3,  9,  0, 16, 25])

In [16]:
arr

array([1, 3, 9, 0])

In [17]:
np.delete(arr, 0) # Удаление 0-вого по индексу элемента

array([3, 9, 0])

In [18]:
np.delete(arr, [0, 1], axis=None) # Нескольких

array([9, 0])

In [19]:
arr

array([1, 3, 9, 0])

---

Массивы также можно сортировать с помощью функции $\mathsf{np.sort}$:

In [20]:
np.sort(arr)

array([0, 1, 3, 9])

In [21]:
arr

array([1, 3, 9, 0])

---

Массивы можно конкатенировать между собой с помощью $\mathsf{np.concatenate}$:

In [22]:
a = np.array([1, 4])
b = np.array([9, 16])
c = np.array([25, 36])

np.concatenate((a, b, c))

array([ 1,  4,  9, 16, 25, 36])

In [23]:
a, b, c

(array([1, 4]), array([ 9, 16]), array([25, 36]))

---